[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.build]
cmds = ["npm ci --include=dev", "npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_VERSION = "20.11.0"
NPM_VERSION = "10.2.4"