apiVersion: v1
kind: Secret
metadata:
  name: basalam-secrets
  namespace: basalam-product-manager
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==  # your-super-secret-jwt-key
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWNyZXQtcmVmcmVzaC1rZXk=  # your-super-secret-refresh-key
  BASALAM_CLIENT_ID: eW91ci1iYXNhbGFtLWNsaWVudC1pZA==  # your-basalam-client-id
  BASALAM_CLIENT_SECRET: eW91ci1iYXNhbGFtLWNsaWVudC1zZWNyZXQ=  # your-basalam-client-secret
  ADMIN_CARD_NUMBER: MTIzNDU2Nzg5MDEyMzQ1Ng==  # 1234567890123456